// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateAccount(arg1) {
  return window['go']['main']['App']['ActivateAccount'](arg1);
}

export function CancelOpenAIAuth() {
  return window['go']['main']['App']['CancelOpenAIAuth']();
}

export function CheckUpstreamStatus() {
  return window['go']['main']['App']['CheckUpstreamStatus']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetCodexAuthInfo() {
  return window['go']['main']['App']['GetCodexAuthInfo']();
}

export function GetEnvironmentConfig() {
  return window['go']['main']['App']['GetEnvironmentConfig']();
}

export function GetSelectedCodexProcessLauncherKeys() {
  return window['go']['main']['App']['GetSelectedCodexProcessLauncherKeys']();
}

export function GetSelectedCodexProcessPIDs() {
  return window['go']['main']['App']['GetSelectedCodexProcessPIDs']();
}

export function GetUpstreamConfig() {
  return window['go']['main']['App']['GetUpstreamConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InjectActiveAccountToCodexProcess(arg1) {
  return window['go']['main']['App']['InjectActiveAccountToCodexProcess'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function QuitApplication() {
  return window['go']['main']['App']['QuitApplication']();
}

export function RefreshAccountCredential(arg1) {
  return window['go']['main']['App']['RefreshAccountCredential'](arg1);
}

export function RefreshAccountUsage() {
  return window['go']['main']['App']['RefreshAccountUsage']();
}

export function SaveUpstreamConfig(arg1) {
  return window['go']['main']['App']['SaveUpstreamConfig'](arg1);
}

export function ScanCodexAuth() {
  return window['go']['main']['App']['ScanCodexAuth']();
}

export function ScanCodexAuthPath() {
  return window['go']['main']['App']['ScanCodexAuthPath']();
}

export function ScanCodexProcesses() {
  return window['go']['main']['App']['ScanCodexProcesses']();
}

export function SetSelectedCodexProcessLauncherKeys(arg1) {
  return window['go']['main']['App']['SetSelectedCodexProcessLauncherKeys'](arg1);
}

export function SetSelectedCodexProcessPIDs(arg1) {
  return window['go']['main']['App']['SetSelectedCodexProcessPIDs'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartOpenAIAuth() {
  return window['go']['main']['App']['StartOpenAIAuth']();
}

export function UpdateCodexMemoryProfileConfig() {
  return window['go']['main']['App']['UpdateCodexMemoryProfileConfig']();
}
