// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateAccount(arg1:number):Promise<main.AccountInfo>;

export function CancelOpenAIAuth():Promise<void>;

export function CheckUpstreamStatus():Promise<main.UpstreamStatus>;

export function DeleteAccount(arg1:number):Promise<void>;

export function GetCodexAuthInfo():Promise<main.CodexAuthInfo>;

export function GetEnvironmentConfig():Promise<main.EnvironmentConfig>;

export function GetSelectedCodexProcessPIDs():Promise<Array<number>>;

export function GetUpstreamConfig():Promise<main.UpstreamConfig>;

export function Greet(arg1:string):Promise<string>;

export function InjectActiveAccountToCodexProcess(arg1:number):Promise<void>;

export function ListAccounts():Promise<Array<main.AccountInfo>>;

export function QuitApplication():Promise<void>;

export function RefreshAccountCredential(arg1:number):Promise<main.AccountInfo>;

export function RefreshAccountUsage():Promise<void>;

export function SaveUpstreamConfig(arg1:main.UpstreamConfig):Promise<main.UpstreamConfig>;

export function ScanCodexAuth():Promise<main.CodexAuthInfo>;

export function ScanCodexAuthPath():Promise<main.CodexAuthInfo>;

export function ScanCodexProcesses():Promise<Array<main.CodexProcessInfo>>;

export function SetSelectedCodexProcessPIDs(arg1:Array<number>):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartOpenAIAuth():Promise<void>;
